### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by avtobiff** [korginc/volcasample#4]
Please version and tag releases, semantic versioning is widely used.

In #3 the soname has a hardcoded placeholder version of `1.0.0`, this
should be generated from a release version.

**Comment by Hideki-Fujii** [comment]
Thank you pointed out.
We are going to be addressed in a few days.

**Comment by avtobiff** [comment]
Great!

I want to package this for Debian and need a soname.

**Comment by avtobiff** [comment]
#5 assumes that tags are named `x.y.z` (or `x.y`) where x, y are digits.

**Comment by Hideki-Fujii** [comment]
I've create a 'tag 1.0.0' to initial release.
And　we've check the operation of the #5.

We will add APIs to get version.
Then, I will create a new tag.

**Comment by avtobiff** [comment]
On Tue, Dec 9, 2014 at 8:00 AM, Hideki-Fujii notifications@github.com wrote:

> I've create a 'tag 1.0.0' to initial release.
> And　we've check the operation of the #5.

Great!

I verified that it works locally myself before sending a pull request
of course.

> We will add APIs to get version.

I don't understand what you mean...

> Then, I will create a new tag.

Now when you have created a tag you need to stick by it.

http://schacon.github.io/git/git-tag#_on_re_tagging
