### ISSUE TITLE
Please name example binaries consistently 

### ISSUE THREAD

**Issue by avtobiff** [korginc/volcasample#7]
In 0a5568e the name of binary in the GNU/Linux example script was
changed to read just `example` instead of `exsample`.

The source file, however, is named `exsample` and this is also what is
used in other project files.

Please name the example binaries consistently, either `example` or
`exsample` everywhere.

**Comment by Hideki-Fujii** [comment]
Oh... It is my mistake, thank you.
We have modified the name of source file, the project file to use it 
and the name of execute file for Mac.
(From 'exsample' to 'example'.)

**Comment by avtobiff** [comment]
Closing since it is fixed with 2c40c3a.
