### ISSUE TITLE
Volca Sample with 200 samples?

### ISSUE THREAD

**Issue by josephernest** [korginc/volcasample#9]
The Korg Volca Sample is wonderful but 100 samples memory is a bit short...

The problem is that when you use the Volca Sample _for the first time_, you _immediately_ have to delete some factory samples, if you want to upload user samples, because the memory is already full when you first use it!

Do you think it could be possible with an update to have :
S000 to S099 = factory samples
S100 to S199 = user samples 

(With a firmware mod, or something else)

**Comment by tats-t** [comment]
Unfortunately, the limitation is with the 4MB memory size, not the sample number so there's no way of avoiding the initial delete stage. BTW neat tool!

**Comment by josephernest** [comment]
In terms of _User Experience_ / _product philosophy_, asking the user to destroy/delete things, as the FIRST thing to do when unpacking a product, is not very nice  (in a philosophical point of view).

Why not have 8MB memory in the product and let 4MB free?
So the user is not "annoyed" by having to loose things at the start of the user experience (loosing things involves making choices => which sample to delete?  => this is hard  ;) )

**Comment by sotimely** [comment]
Even limited to 4 MB it would be nice to not be arbitrarily limited to 100 samples. I replaced a lot of the samples and still am using far less than the 4 MB, yet I am hitting the 100 sample limit.
